DEFAULT_TICKER = "AAPL"
DEFAULT_START_DATE = "2020-01-01"
DEFAULT_END_DATE = None  # auto: latest available
DEFAULT_LOOKBACK_DAYS = 252  # 1 trading year 

DEFAULT_N_SIMULATIONS = 2000
DEFAULT_FORECAST_HORIZON = 252  # trading day
DEFAULT_SEED = 42

DEFAULT_CONFIDENCE_LEVEL = 0.05  # VaR
RISK_FREE_RATE = 0.05  # 5% annual
TRADING_DAYS = 252
